"""initial setup

Revision ID: adcbbb2c012d
Revises: 
Create Date: 2025-10-21 15:07:06.915616

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "adcbbb2c012d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
